name: health_icons
description: "A Flutter package for health icons as Static font."
version: 0.0.1
homepage: https://github.com/devnoaman/health_icons.git

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: HealthIcons
      fonts:
        - asset: fonts/healthicons.ttf
